services:
  webscraper:
    build:
      context: .     
      dockerfile: docker/Dockerfile
    container_name: mcp_webscraper_container
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true          # | Estes dois andam de mão dada. Enquanto o stdin_open (Standard Input, mantém o stdin aberto, permitindo interações)
    tty: true                 # |Enquanto o tty (Teletypewritter) aloca um terminal, com o stdin